=== UO294013/VisitLaviana/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="fecha_inicio" />
				<xs:element minOccurs="0" ref="hora_inicio" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personas_recomendadas" />
				<xs:element ref="lugar_inicio" />
				<xs:element ref="direccion_inicio" />
				<xs:element ref="coordenadas_inicio" />
				<xs:element ref="referencias" />
                <xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tipo_ruta" type="xs:string" use="required" />
			<xs:attribute name="medio_transporte" type="xs:string" use="required" />
			<xs:attribute name="duracion" type="xs:string" use="required" />
            <xs:attribute name="nivel_recomendacion" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha_inicio" type="xs:date" />
	<xs:element name="hora_inicio" type="xs:time" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personas_recomendadas" type="xs:string" />
	<xs:element name="lugar_inicio" type="xs:string" />
    <xs:element name="direccion_inicio" type="xs:string" />
    <xs:element name="coordenadas_inicio" >
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
    <xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="5" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito" >
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="descripcion_hito" />
				<xs:element ref="coordenadas_hito" />
				<xs:element ref="distancia" />
                <xs:element ref="fotos_hito" />
                <xs:element minOccurs="0" ref="videos_hito" />
			</xs:sequence>
            <xs:attribute name="nombre_hito" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:element name="descripcion_hito" type="xs:string" />
    <xs:element name="coordenadas_hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="distancia">
		<xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="unidad" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
	</xs:element>
	<xs:element name="fotos_hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos_hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-90.00"></xs:minInclusive>
								<xs:maxInclusive value="90.00"></xs:maxInclusive>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="latitud">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-90.00"></xs:minInclusive>
								<xs:maxInclusive value="90.00"></xs:maxInclusive>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="altitud">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="0.00"></xs:minInclusive>
								<xs:maxInclusive value="8000.00"></xs:maxInclusive>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO294013/VisitLaviana/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es rutas.xsd" >
    <ruta nombre="Ruta Senda Verde: El Sutu - La Vara" tipo_ruta="Pasisajística y de senderismo" medio_transporte="A pie o en bicicleta" duracion="7 horas" nivel_recomendacion="7">
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta poco concurrida, de dificultad moderada por su longitud (16 kilómetros aproximadamente). Se recomienda llevar calzado cómodo. Paisajes muy bonitos, sendas bien cuidadas y buen terreno.</descripcion>
        <personas_recomendadas>Para gente con buena forma física</personas_recomendadas>
        <lugar_inicio>Parking de Plaza Fray Ceferino (núcleo de Pola de Laviana)</lugar_inicio>
        <direccion_inicio>Hacia el puente de hierro del Sutu</direccion_inicio>
        <coordenadas_inicio>
            <coordenada longitud="-5.566287" latitud="43.247423" altitud="287"></coordenada> 
        </coordenadas_inicio>
        <referencias>
            <referencia>https://www.ayto-laviana.es/rutas-y-senderismo</referencia>
            <referencia>https://culturalavianaturismo.blogspot.com/p/el-sutu-la-vara.html</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/hormiguita-circular-el-sutu-pico-la-vara-asturias-114006348</referencia>
        </referencias>
        <hitos>
            <hito nombre_hito="Puente de hierro del Sutu">
                <descripcion_hito>Puente de hierro que conecta el corazón de Pola de Laviana con el Polígono del Sutu. Antiguamente era utilizado por los trenes mineros para llevar carbón a la estación de ferrocarril de Langreo</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.567169" latitud="43.247412" altitud="285"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">74</distancia> <!-- Distancia desde la salida -->
                <fotos_hito>
                    <foto>multimedia/imagenes/puente_del_sutu.jpg</foto>
                    <foto>multimedia/imagenes/puente_del_sutu2.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Fuente Les Sinariegues">
                <descripcion_hito>Pequeña fuente al inicio del trayecto, aún en el Polígono del Sutu y cerca del inicio de la senda</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.569519" latitud="43.245197" altitud="332"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">484.82</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/fuente_les_sinariegues.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Mirador del Cantiquín">
                <descripcion_hito>Mirador en el Coto Musel con preciosas vistas de Pola de Laviana</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.572721" latitud="43.246342" altitud="424"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">944.79</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/cantiquin.jpg</foto>
                    <foto>multimedia/imagenes/cantiquin2.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Cartel informativo: Senderos del carbón">
                <descripcion_hito>Cartel informativo con bancoy buenas vistas</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.594737" latitud="43.239518" altitud="864"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">4429.08</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/senderos_carbon.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Banco mirador del Pico de la Vara">
                <descripcion_hito>Banco en un descanso a escasos metros de la llegada al Pico de la Vara. Impresionantes vistas del concejo</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.595520" latitud="43.236037" altitud="926"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">461.28</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/banco.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Pico de la Vara">
                <descripcion_hito>Alto del Pico de la Vara, con una elevación máxima de 949 metros</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.595278" latitud="43.237023" altitud="946"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">128.71</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/pico_la_vara.jpg</foto>
                </fotos_hito>
            </hito>
        </hitos>
    </ruta>
    <ruta nombre="Ruta Foces del Raigosu" tipo_ruta="Paisajística" medio_transporte="A pie" duracion="4 horas" nivel_recomendacion="9">
        <fecha_inicio>2025-07-25</fecha_inicio>
        <hora_inicio>10:00:00</hora_inicio>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta de alto valor turístico y paisajístico, de baja dificultad y con poco desnivel (en torno a 700 metros de subida en 7 kilómetros de trayecto). Comienza en el paraje de Mestres y finaliza en Los Collaos, continuando siempre paralela al Río Raigosu</descripcion>
        <personas_recomendadas>Se pueden llevar niños</personas_recomendadas>
        <lugar_inicio>Les Mestres, al oeste de Fombermeja</lugar_inicio>
        <direccion_inicio>Camino de tierra de Les Mestres</direccion_inicio>
        <coordenadas_inicio>
            <coordenada longitud="-5.530605" latitud="43.202860" altitud="458"></coordenada> 
        </coordenadas_inicio>
        <referencias>
            <referencia>https://es.wikiloc.com/rutas-senderismo/foces-del-raigosu-pr-as-290-142715472</referencia>
            <referencia>https://culturalavianaturismo.blogspot.com/p/ruta-foces-del-raigosu_21.html</referencia>
            <referencia>https://www.ayto-laviana.es/rutas-y-senderismo</referencia>
        </referencias>
        <hitos>
            <hito nombre_hito="Zona de descanso en la Foz de Cebellales">
                <descripcion_hito>Apartadero en el camino con varios bancos con mesa para descansar y disfrutar de la naturaleza. Aproximadamente en la mitad del camino</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.532799" latitud="43.180651" altitud="711"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="kilómetros">3.33</distancia> <!-- Distancia desde la salida -->
                <fotos_hito>
                    <foto>multimedia/imagenes/descanso.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Semitúnel de piedra">
                <descripcion_hito>Pasadizo de piedra en medio del sendero con un semitúnel rocoso descubierto</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.530219" latitud="43.177587" altitud="817"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">800</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/semitunel.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Mirador sobre las casas del Raigosu">
                <descripcion_hito>Mirador con vistas impresionantes del valle, situado en un desvío a escasos metros de las casas y cabañas del Raigosu</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.527284" latitud="43.176189" altitud="911"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="kilómetros">1.1</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/mirador_inter.jpg</foto>
                    <foto>multimedia/imagenes/mirador.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Abrevadero para ganado">
                <descripcion_hito>Pequeña fuente para el ganado, a mitad de la subida entre las cabañas del Raigosu y las cabañas de la Carba de Los Collaos</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.523808" latitud="43.173521" altitud="1039"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="metros">950</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/abrevadero.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Cabañas de la Carba de Los Collaos">
                <descripcion_hito>Cabañas de piedra a los pies de la Carba de Los Collaos</descripcion_hito>
                <coordenadas_hito>
                    <coordenada longitud="-5.521102" latitud="43.173476" altitud="1125"></coordenada> 
                </coordenadas_hito>
                <distancia unidad="kilómetros">1.3</distancia>
                <fotos_hito>
                    <foto>multimedia/imagenes/carba.jpg</foto>
                    <foto>multimedia/imagenes/señales.jpg</foto>
                </fotos_hito>
            </hito>
            <hito nombre_hito="Mirador en Los Collaos">
